"""add folder_watches

Revision ID: 8f15aae7bc46
Revises: 8a80caa549c7
Create Date: 2026-06-12 15:27:31.345735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f15aae7bc46'
down_revision: Union[str, None] = '8a80caa549c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('folder_path', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folder_watches_event_id'), 'folder_watches', ['event_id'], unique=True)
    op.create_index(op.f('ix_folder_watches_id'), 'folder_watches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folder_watches_id'), table_name='folder_watches')
    op.drop_index(op.f('ix_folder_watches_event_id'), table_name='folder_watches')
    op.drop_table('folder_watches')
    # ### end Alembic commands ###
